<a href="https://colab.research.google.com/github/pedro162/machine_learn/blob/main/algoritmo_k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install plotly --upgrade

In [2]:
import plotly.express as spx
import plotly.graph_objects as go
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.cluster import KMeans

In [4]:
x = [20,27,21,37,46,53,55,47,52,32,39,41,39,48,48]
y = [1000, 1200, 1900, 1850, 900, 950, 2000, 2100, 3000,5000,4100,5100,7000,5000,6500]

In [5]:
grapthc = spx.scatter(x=x,y=y)
grapthc.show()

In [6]:
salaryDatabase = np.array([
    [20,1000],[27,1200],[21,2900],[37,1850],[46,900],[53,950],[55,2000],[47,2100],[52,3000],[32,5900],
    [39,4100],[41,5100],[39,7000],[48,5000],[48,6500],
])

In [7]:
salaryDatabase

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [8]:
salaryScaler = StandardScaler()
salaryDatabase = salaryScaler.fit_transform(salaryDatabase)

In [9]:
salaryDatabase

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [10]:
salaryKmeans = KMeans(n_clusters=3)
salaryKmeans.fit(salaryDatabase)

KMeans(n_clusters=3)

In [11]:
centoides = salaryKmeans.cluster_centers_

In [12]:
centoides

array([[-1.63312883, -0.77505093],
       [ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572]])

In [13]:
salaryScaler.inverse_transform(salaryKmeans.cluster_centers_)

array([[  22.66666667, 1700.        ],
       [  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ]])

In [14]:
labels = salaryKmeans.labels_

In [15]:
labels

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int32)

In [16]:
grapthc_1 = spx.scatter(x=salaryDatabase[:,0],y=salaryDatabase[:,1],color=labels)
grapthc_2 = spx.scatter(x=centoides[:,0],y=centoides[:,1], size=[12, 12, 12])
#grapthc_1.show()
grapthc_3 = go.Figure(data=grapthc_1.data + grapthc_2.data)
grapthc_3.show()


In [17]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [18]:
creadCardDatabase = pd.read_csv('/content/drive/MyDrive/credit_card_clients.csv', header=1)
creadCardDatabase

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [19]:
creadCardDatabase['BILL_TOTAL'] = creadCardDatabase['BILL_AMT1'] + creadCardDatabase['BILL_AMT2'] + creadCardDatabase['BILL_AMT3'] + creadCardDatabase['BILL_AMT4'] + creadCardDatabase['BILL_AMT5'] + creadCardDatabase['BILL_AMT6']

In [20]:
creadCardDatabase

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0         -1  ...          0          0         0       689         0   
1          0  ...       3455       3261         0      1000      1000   
2          0  ...      14948      15549      1518      1500      1000   
3          0  ...      28959      29547      2000      2019      1200   
4          0  ...      19146      19131      2000     36681     10000   
...      ...  ...        ...        ...       ...       ...       ...   
29995      0  ...      31237      15980      8500     20000      5003   
29996     -1  ...       5190          0      1837      3526      8998   
29997     -1  ...      20582      19357         0         0     22000   
29998      0  ...      11855      48944     85900      3409      1178   
29999      0  ...      32428      15313      2078      1800      1430   

       PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  BILL_TOTAL  
0             0         0         0                           1        7704  
1          1000         0      2000                           1       17077  
2          1000      1000      5000                           0      101653  
3          1100      1069      1000                           0      231334  
4          9000       689       679                           0      109339  
...         ...       ...       ...                         ...         ...  
29995      3047      5000      1000                           0      725349  
29996       129         0         0                           0       21182  
29997      4200      2000      3100                           1       70496  
29998      1926     52964      1804                           1      266611  
29999      1000      1000      1000                           1      230874  

[30000 rows x 26 columns]

In [21]:
X_credCard = creadCardDatabase.iloc[:,[1,25]].values
X_credCard

array([[ 20000,   7704],
       [120000,  17077],
       [ 90000, 101653],
       ...,
       [ 30000,  70496],
       [ 80000, 266611],
       [ 50000, 230874]])

In [22]:
credCarScaler = StandardScaler()
X_credCard = credCarScaler.fit_transform(X_credCard)
X_credCard

array([[-1.13672015, -0.69069198],
       [-0.3659805 , -0.66599747],
       [-0.59720239, -0.44316987],
       ...,
       [-1.05964618, -0.52525745],
       [-0.67427636, -0.00856436],
       [-0.90549825, -0.10271861]])

In [23]:
wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i, random_state=0)
  kmeans.fit(X_credCard)
  wcss.append(kmeans.inertia_)

In [24]:
wcss

[59999.99999999962,
 35197.83439125732,
 20128.20263562325,
 15892.249716910846,
 10708.603774943429,
 8604.404544864514,
 7684.904846136829,
 6593.001391781384,
 5669.721586002757,
 5055.083531903275]

In [25]:
grapthc = spx.line(x=range(1,11), y=wcss)
grapthc.show()

In [26]:
credCardKeyMeans = KMeans(n_clusters=4, random_state=0)
credCardKeyMeans.fit_predict(X_credCard)

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [27]:
grapthc = spx.scatter(x=X_credCard[:,0],y=X_credCard[:,1],color=credCardKeyMeans.labels_)
grapthc.show()

In [28]:
clientList = np.column_stack((creadCardDatabase,credCardKeyMeans.labels_))
clientList

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [     2, 120000,      2, ...,      1,  17077,      0],
       [     3,  90000,      2, ...,      0, 101653,      0],
       ...,
       [ 29998,  30000,      1, ...,      1,  70496,      0],
       [ 29999,  80000,      1, ...,      1, 266611,      0],
       [ 30000,  50000,      1, ...,      1, 230874,      0]])

In [29]:
clientList = clientList[clientList[:, 26].argsort()]
clientList

array([[ 18952,  40000,      2, ...,      1,  54315,      0],
       [ 23139, 120000,      2, ...,      0,  35087,      0],
       [ 23142,  20000,      2, ...,      1,      0,      0],
       ...,
       [ 29980, 180000,      1, ...,      0,      0,      3],
       [ 29990, 150000,      1, ...,      0,  13211,      3],
       [ 29930, 170000,      1, ...,      1,  12628,      3]])

In [30]:
X_CredCardPlus = creadCardDatabase.iloc[:,[1,2,3,4,5,25]].values
X_CredCardPlus

array([[ 20000,      2,      2,      1,     24,   7704],
       [120000,      2,      2,      2,     26,  17077],
       [ 90000,      2,      2,      2,     34, 101653],
       ...,
       [ 30000,      1,      2,      2,     37,  70496],
       [ 80000,      1,      3,      1,     41, 266611],
       [ 50000,      1,      2,      1,     46, 230874]])

In [31]:
credCardPlusScaler = StandardScaler()
X_CredCardPlus = credCardPlusScaler.fit_transform(X_CredCardPlus)
X_CredCardPlus

array([[-1.13672015,  0.81016074,  0.18582826, -1.05729503, -1.24601985,
        -0.69069198],
       [-0.3659805 ,  0.81016074,  0.18582826,  0.85855728, -1.02904717,
        -0.66599747],
       [-0.59720239,  0.81016074,  0.18582826,  0.85855728, -0.16115646,
        -0.44316987],
       ...,
       [-1.05964618, -1.23432296,  0.18582826,  0.85855728,  0.16430256,
        -0.52525745],
       [-0.67427636, -1.23432296,  1.45111372, -1.05729503,  0.59824792,
        -0.00856436],
       [-0.90549825, -1.23432296,  0.18582826, -1.05729503,  1.14067961,
        -0.10271861]])

In [32]:
wcss= []

for i in range(1,11):
  kmeans = KMeans(n_clusters=i, random_state=0)
  kmeans.fit(X_CredCardPlus)
  wcss.append(kmeans.inertia_)

In [33]:
wcss

[179999.99999999919,
 143649.52707155238,
 123753.77414684519,
 108637.13498619615,
 95861.59977561921,
 87713.05625167926,
 80306.61463004285,
 75916.5676661599,
 72999.41644900985,
 69831.28289477261]

In [34]:
grapthc = spx.line(x=range(1,11), y=wcss)
grapthc.show()

In [35]:
credCardPlusKeyMeans = KMeans(n_clusters=2, random_state=0)
labels = credCardPlusKeyMeans.fit_predict(X_CredCardPlus)
labels

array([0, 1, 1, ..., 1, 0, 0], dtype=int32)

In [36]:
from sklearn.decomposition import PCA


In [37]:
pca = PCA(n_components=2)
X_credCardPlusPCA = pca.fit_transform(X_CredCardPlus)
X_credCardPlusPCA

array([[-0.74082054, -1.13671858],
       [-1.48027121, -0.30100547],
       [-0.94737386, -0.48666789],
       ...,
       [-0.79468657, -0.90012663],
       [ 1.17562376, -1.54746987],
       [ 1.13614987, -1.14039836]])

In [38]:
X_credCardPlusPCA.shape

(30000, 2)

In [39]:
grapthc = spx.scatter(x=X_credCardPlusPCA[:,0],y=X_credCardPlusPCA[:,1],color=labels)
grapthc.show()

In [40]:
clientList = np.column_stack((creadCardDatabase,labels))
clientList = clientList[clientList[:, 26].argsort()]
clientList

array([[    19, 360000,      2, ...,      0,      0,      0],
       [    22, 120000,      2, ...,      1,   1896,      0],
       [    24, 450000,      2, ...,      1,  26965,      0],
       ...,
       [    36, 160000,      1, ...,      0,  25312,      1],
       [ 29977,  40000,      1, ...,      1, 306009,      1],
       [    33, 100000,      1, ...,      0, 495237,      1]])

In [42]:
from sklearn.datasets import make_blobs

In [59]:
X_random, y_random = make_blobs(n_samples=200, centers=5, random_state=1)

In [60]:
X_random

array([[-1.96576392e+00,  5.23446451e+00],
       [-5.16022348e+00, -7.04217141e+00],
       [-6.17937069e+00, -2.16733539e+00],
       [-7.39138168e+00, -9.49590389e+00],
       [-6.38481234e+00, -8.47302970e+00],
       [-6.26144310e+00, -3.78347905e+00],
       [-2.04278768e+00,  3.07660864e-01],
       [-4.46426086e+00, -4.39451238e+00],
       [-6.40386190e+00, -6.36106990e+00],
       [ 2.42271161e-04,  5.14853403e+00],
       [-5.99212006e+00, -3.91488289e+00],
       [-6.46137477e+00, -3.14560994e+00],
       [-4.10185174e+00, -1.16625450e+00],
       [-1.01341572e+01, -4.07240274e+00],
       [-5.99004766e+00, -2.82631801e+00],
       [-1.14663009e+00,  4.10839703e+00],
       [-1.17104176e+00,  4.33091816e+00],
       [-9.19585147e+00, -3.90678125e+00],
       [-8.30173556e+00, -7.27738918e+00],
       [-7.56309575e+00, -8.46421308e+00],
       [-1.86845414e+00,  4.99311306e+00],
       [-4.22362233e+00, -2.50312346e+00],
       [-1.90838667e+00,  5.86113655e-01],
       [-6.

In [61]:
y_random

array([0, 2, 3, 2, 2, 3, 4, 3, 2, 0, 3, 3, 4, 1, 3, 0, 0, 1, 2, 2, 0, 3,
       4, 3, 4, 1, 2, 4, 4, 1, 2, 4, 0, 3, 2, 0, 1, 2, 1, 4, 2, 1, 4, 4,
       2, 4, 1, 3, 2, 0, 0, 3, 3, 0, 3, 1, 0, 4, 2, 2, 1, 3, 3, 3, 2, 0,
       0, 1, 4, 2, 1, 4, 2, 4, 4, 1, 2, 3, 0, 4, 1, 1, 3, 2, 3, 0, 2, 2,
       2, 1, 4, 3, 0, 4, 3, 1, 4, 0, 2, 1, 0, 2, 4, 1, 4, 2, 1, 2, 3, 0,
       3, 3, 2, 1, 3, 0, 1, 4, 0, 0, 2, 1, 1, 3, 0, 1, 2, 4, 2, 4, 0, 4,
       3, 3, 1, 1, 3, 0, 0, 3, 3, 3, 0, 0, 4, 2, 4, 0, 2, 3, 4, 3, 0, 4,
       3, 1, 1, 1, 0, 2, 4, 0, 1, 0, 4, 1, 1, 1, 3, 4, 1, 4, 4, 3, 0, 2,
       4, 3, 2, 0, 2, 0, 0, 2, 1, 4, 1, 0, 0, 3, 2, 4, 0, 1, 1, 4, 3, 4,
       2, 1])

In [62]:
graphic = spx.scatter(x=X_random[:,0], y=X_random[:,1])
graphic.show()

In [64]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(X_random)

KMeans(n_clusters=5)

In [65]:
centroids = kmeans.cluster_centers_
centroids

array([[-1.58338528,  4.50520457],
       [-5.90368078, -3.04489641],
       [-9.85620522, -3.91021738],
       [-6.87958999, -8.11648104],
       [-2.17069756,  1.02591979]])

In [69]:
labels = kmeans.labels_

In [71]:
graphic1 = spx.scatter(x=X_random[:,0], y=X_random[:,1], color=labels)
graphic2 = spx.scatter(x=centroids[:,0], y=centroids[:,1], size=[12, 12, 12, 12, 12])
graphic3 = go.Figure(data=graphic1.data + graphic2.data)
graphic3.show()