<a href="https://colab.research.google.com/github/pedro162/machine_learn/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import plotly.express as spx
import plotly.graph_objects as go
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
census_dataset = pd.read_csv("/content/drive/MyDrive/census.csv")
census_dataset

age          workclass  final-weight    education  education-num  \
0       39          State-gov         77516    Bachelors             13   
1       50   Self-emp-not-inc         83311    Bachelors             13   
2       38            Private        215646      HS-grad              9   
3       53            Private        234721         11th              7   
4       28            Private        338409    Bachelors             13   
...    ...                ...           ...          ...            ...   
32556   27            Private        257302   Assoc-acdm             12   
32557   40            Private        154374      HS-grad              9   
32558   58            Private        151910      HS-grad              9   
32559   22            Private        201490      HS-grad              9   
32560   52       Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   
32560   Female         15024             0             40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [3]:
X_census = census_dataset.iloc[:, 0:14].values
X_census

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [4]:
y_census = census_dataset.iloc[:, 14].values
y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

In [6]:
X_census[:, 1] = label_encoder_workclass.fit_transform(X_census[:, 1])
X_census[:, 3] = label_encoder_education.fit_transform(X_census[:, 3])
X_census[:, 5] = label_encoder_marital.fit_transform(X_census[:, 5])
X_census[:, 6] = label_encoder_occupation.fit_transform(X_census[:, 6])
X_census[:, 7] = label_encoder_relationship.fit_transform(X_census[:, 7])
X_census[:, 8] = label_encoder_race.fit_transform(X_census[:, 8])
X_census[:, 9] = label_encoder_sex.fit_transform(X_census[:, 9])
X_census[:, 13] = label_encoder_country.fit_transform(X_census[:, 13])

In [7]:
X_census[0]

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 39], dtype=object)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_census = scaler.fit_transform(X_census)

In [9]:
X_census

array([[ 0.03067056,  2.15057856, -1.06361075, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [ 0.83710898,  1.46373585, -1.008707  , ..., -0.21665953,
        -2.22215312,  0.29156857],
       [-0.04264203,  0.09005041,  0.2450785 , ..., -0.21665953,
        -0.03542945,  0.29156857],
       ...,
       [ 1.42360965,  0.09005041, -0.35877741, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [-1.21564337,  0.09005041,  0.11095988, ..., -0.21665953,
        -1.65522476,  0.29156857],
       [ 0.98373415,  0.77689313,  0.92989258, ..., -0.21665953,
        -0.03542945,  0.29156857]])

In [10]:
from sklearn.model_selection import train_test_split
X_census_train, X_census_test, y_census_train, y_census_test = train_test_split(X_census, y_census, test_size=0.15, random_state=0)

In [11]:
X_census_train.shape, X_census_test.shape

((27676, 14), (4885, 14))

### PCA (Principal Component Analysis)

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components=8)
X_census_train_pca = pca.fit_transform(X_census_train)
X_census_test_pca = pca.transform(X_census_test)

In [13]:
X_census_train_pca.shape, X_census_test_pca.shape

((27676, 8), (4885, 8))

In [14]:
X_census_train_pca

array([[-0.72756979, -0.63707837,  0.92959677, ..., -0.4750941 ,
         1.26767572, -0.70907366],
       [-1.94861194,  0.52336888,  0.11546966, ..., -0.20608772,
        -0.28547192, -1.10996543],
       [-0.90984576, -0.49631087, -0.21043617, ..., -0.22000605,
         1.54790866, -0.6082255 ],
       ...,
       [ 1.55068874,  1.8706316 ,  1.18829813, ...,  0.15217589,
        -1.23888631,  0.23631102],
       [-1.50148337,  0.90027   , -1.39911867, ..., -0.83827868,
        -0.03400375,  0.51140853],
       [-0.39972037,  0.73809833,  0.78746921, ..., -0.39215363,
        -0.75329109, -0.00358243]])

In [15]:
pca.explained_variance_ratio_

array([0.151561  , 0.10109701, 0.08980379, 0.08076277, 0.07627678,
       0.07357646, 0.06772289, 0.06690789])

In [16]:
pca.explained_variance_ratio_.sum()

0.7077085943199315

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
random_forest_census_pca = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)
random_forest_census_pca.fit(X_census_train_pca, y_census_train)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [18]:
predictions = random_forest_census_pca.predict(X_census_test_pca)
accuracy_score(y_census_test, predictions)

0.8343909928352098

In [19]:
predictions

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [20]:
y_census_test

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

###Kernel PCA

In [21]:
from sklearn.decomposition import KernelPCA

In [22]:
kpca = KernelPCA(n_components=8, kernel='rbf')
X_census_train_kpca = kpca.fit_transform(X_census_train)
X_census_test_kpca = kpca.transform(X_census_test)

In [23]:
X_census_train_kpca.shape, X_census_test_kpca.shape

((27676, 8), (4885, 8))

In [24]:
X_census_train_kpca

array([[ 0.18894283,  0.05517031, -0.08653531, ...,  0.41350358,
         0.06383854, -0.25147161],
       [ 0.16165577, -0.07855932, -0.03858728, ..., -0.01994034,
        -0.00338877, -0.29452204],
       [-0.085163  , -0.27486159,  0.12920466, ...,  0.19029531,
         0.04692292,  0.13187157],
       ...,
       [-0.27872683,  0.40033469,  0.20104327, ..., -0.17392304,
        -0.16108872,  0.00683154],
       [ 0.21829898, -0.12392098, -0.02312817, ..., -0.12231089,
         0.33364887,  0.25177643],
       [ 0.24961467,  0.42418174,  0.12141394, ..., -0.00408799,
        -0.18258341, -0.08239723]])

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
random_forest_census_kpca = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)
random_forest_census_kpca.fit(X_census_train_kpca, y_census_train)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [26]:
predictions = random_forest_census_kpca.predict(X_census_test_kpca)
accuracy_score(y_census_test, predictions)

0.826202661207779

In [27]:
predictions

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [28]:
y_census_test

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

###LDA

In [40]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=1)

In [41]:
X_census_train_lda = lda.fit_transform(X_census_train, y_census_train)
X_census_test_lda = lda.transform(X_census_test)

In [42]:
X_census_train_lda.shape, X_census_test_lda.shape

((27676, 1), (4885, 1))

In [43]:
X_census_train_lda

array([[-0.30226006],
       [ 0.64945145],
       [ 1.57912192],
       ...,
       [-1.37887999],
       [ 2.44698101],
       [-0.19212323]])

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

random_forest_census_lda = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)
random_forest_census_lda.fit(X_census_train_lda, y_census_train)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [45]:
predictions = random_forest_census_lda.predict(X_census_test_lda)
predictions
accuracy_score(y_census_test, predictions)

0.7334698055271238

In [46]:
predictions

array([' <=50K', ' >50K', ' <=50K', ..., ' >50K', ' >50K', ' >50K'],
      dtype=object)

In [47]:
y_census_test

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)