<a href="https://colab.research.google.com/github/pedro162/machine_learn/blob/main/machine_learn_outros_tipos_regressao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

#Regressão polinomial

##Base plano de saúde

In [7]:
base_plano_saude2 = pd.read_csv('/content/drive/MyDrive/Bases de dados/plano_saude2.csv')

In [8]:
base_plano_saude2

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [9]:
X_plano_saude2 = base_plano_saude2.iloc[:,0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:,1].values

In [10]:
X_plano_saude2, y_plano_saude2

(array([[18],
        [23],
        [28],
        [33],
        [38],
        [43],
        [48],
        [53],
        [58],
        [63]]),
 array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
        10100]))

In [11]:
from sklearn.preprocessing import PolynomialFeatures

In [12]:
poly = PolynomialFeatures(degree = 4)
X_plano_saude2_poly = poly.fit_transform(X_plano_saude2)


In [13]:
X_plano_saude2.shape, X_plano_saude2_poly.shape

((10, 1), (10, 5))

In [14]:
X_plano_saude2_poly

array([[1.0000000e+00, 1.8000000e+01, 3.2400000e+02, 5.8320000e+03,
        1.0497600e+05],
       [1.0000000e+00, 2.3000000e+01, 5.2900000e+02, 1.2167000e+04,
        2.7984100e+05],
       [1.0000000e+00, 2.8000000e+01, 7.8400000e+02, 2.1952000e+04,
        6.1465600e+05],
       [1.0000000e+00, 3.3000000e+01, 1.0890000e+03, 3.5937000e+04,
        1.1859210e+06],
       [1.0000000e+00, 3.8000000e+01, 1.4440000e+03, 5.4872000e+04,
        2.0851360e+06],
       [1.0000000e+00, 4.3000000e+01, 1.8490000e+03, 7.9507000e+04,
        3.4188010e+06],
       [1.0000000e+00, 4.8000000e+01, 2.3040000e+03, 1.1059200e+05,
        5.3084160e+06],
       [1.0000000e+00, 5.3000000e+01, 2.8090000e+03, 1.4887700e+05,
        7.8904810e+06],
       [1.0000000e+00, 5.8000000e+01, 3.3640000e+03, 1.9511200e+05,
        1.1316496e+07],
       [1.0000000e+00, 6.3000000e+01, 3.9690000e+03, 2.5004700e+05,
        1.5752961e+07]])

In [15]:
X_plano_saude2_poly[0]

array([1.00000e+00, 1.80000e+01, 3.24000e+02, 5.83200e+03, 1.04976e+05])

In [16]:
regressor_saude_polinomial = LinearRegression()
regressor_saude_polinomial.fit(X_plano_saude2_poly, y_plano_saude2)

LinearRegression()

In [17]:
regressor_saude_polinomial.intercept_

16561.97463791193

In [18]:
regressor_saude_polinomial.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [19]:
novo = [[40]]

In [20]:
novo = poly.transform(novo)

In [21]:
regressor_saude_polinomial.predict(novo)

array([1335.33958015])

In [22]:
previsoes = regressor_saude_polinomial.predict(X_plano_saude2_poly)
previsoes

array([ 549.65035464,  345.85081575,  616.53845992,  975.8391595 ,
       1249.06759853, 1472.7272727 , 1894.51048941, 2973.2983677 ,
       5379.16083828, 9993.35664357])

In [23]:
grafiaco = px.scatter(x=X_plano_saude2[:,0], y=y_plano_saude2)
grafiaco.add_scatter(x=X_plano_saude2[:,0], y=previsoes, name='Regressao')
grafiaco.show()

##Base preço das casas

In [24]:
base_casas = pd.read_csv("/content/drive/MyDrive/Bases de dados/house_prices.csv")
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [25]:
base_casas_clone = base_casas.apply(pd.to_numeric, errors='coerce')
base_casas_clone.corr()

id  date     price  bedrooms  bathrooms  sqft_living  \
id             1.000000   NaN -0.016762  0.001286   0.005160    -0.012258   
date                NaN   NaN       NaN       NaN        NaN          NaN   
price         -0.016762   NaN  1.000000  0.308350   0.525138     0.702035   
bedrooms       0.001286   NaN  0.308350  1.000000   0.515884     0.576671   
bathrooms      0.005160   NaN  0.525138  0.515884   1.000000     0.754665   
sqft_living   -0.012258   NaN  0.702035  0.576671   0.754665     1.000000   
sqft_lot      -0.132109   NaN  0.089661  0.031703   0.087740     0.172826   
floors         0.018525   NaN  0.256794  0.175429   0.500653     0.353949   
waterfront    -0.002721   NaN  0.266369 -0.006582   0.063744     0.103818   
view           0.011592   NaN  0.397293  0.079532   0.187737     0.284611   
condition     -0.023783   NaN  0.036362  0.028472  -0.124982    -0.058753   
grade          0.008130   NaN  0.667434  0.356967   0.664983     0.762704   
sqft_above    -0.010842   NaN  0.605567  0.477600   0.685342     0.876597   
sqft_basement -0.005151   NaN  0.323816  0.303093   0.283770     0.435043   
yr_built       0.021380   NaN  0.054012  0.154178   0.506019     0.318049   
yr_renovated  -0.016907   NaN  0.126434  0.018841   0.050739     0.055363   
zipcode       -0.008224   NaN -0.053203 -0.152668  -0.203866    -0.199430   
lat           -0.001891   NaN  0.307003 -0.008931   0.024573     0.052529   
long           0.020799   NaN  0.021626  0.129473   0.223042     0.240223   
sqft_living15 -0.002901   NaN  0.585379  0.391638   0.568634     0.756420   
sqft_lot15    -0.138798   NaN  0.082447  0.029244   0.087175     0.183286   

               sqft_lot    floors  waterfront      view  ...     grade  \
id            -0.132109  0.018525   -0.002721  0.011592  ...  0.008130   
date                NaN       NaN         NaN       NaN  ...       NaN   
price          0.089661  0.256794    0.266369  0.397293  ...  0.667434   
bedrooms       0.031703  0.175429   -0.006582  0.079532  ...  0.356967   
bathrooms      0.087740  0.500653    0.063744  0.187737  ...  0.664983   
sqft_living    0.172826  0.353949    0.103818  0.284611  ...  0.762704   
sqft_lot       1.000000 -0.005201    0.021604  0.074710  ...  0.113621   
floors        -0.005201  1.000000    0.023698  0.029444  ...  0.458183   
waterfront     0.021604  0.023698    1.000000  0.401857  ...  0.082775   
view           0.074710  0.029444    0.401857  1.000000  ...  0.251321   
condition     -0.008958 -0.263768    0.016653  0.045990  ... -0.144674   
grade          0.113621  0.458183    0.082775  0.251321  ...  1.000000   
sqft_above     0.183512  0.523885    0.072075  0.167649  ...  0.755923   
sqft_basement  0.015286 -0.245705    0.080588  0.276947  ...  0.168392   
yr_built       0.053080  0.489319   -0.026161 -0.053440  ...  0.446963   
yr_renovated   0.007644  0.006338    0.092885  0.103917  ...  0.014414   
zipcode       -0.129574 -0.059121    0.030285  0.084827  ... -0.184862   
lat           -0.085683  0.049614   -0.014274  0.006157  ...  0.114084   
long           0.229521  0.125419   -0.041910 -0.078400  ...  0.198372   
sqft_living15  0.144608  0.279885    0.086463  0.280439  ...  0.713202   
sqft_lot15     0.718557 -0.011269    0.030703  0.072575  ...  0.119248   

               sqft_above  sqft_basement  yr_built  yr_renovated   zipcode  \
id              -0.010842      -0.005151  0.021380     -0.016907 -0.008224   
date                  NaN            NaN       NaN           NaN       NaN   
price            0.605567       0.323816  0.054012      0.126434 -0.053203   
bedrooms         0.477600       0.303093  0.154178      0.018841 -0.152668   
bathrooms        0.685342       0.283770  0.506019      0.050739 -0.203866   
sqft_living      0.876597       0.435043  0.318049      0.055363 -0.199430   
sqft_lot         0.183512       0.015286  0.053080      0.007644 -0.129574   
floors           0.523885      -0.245705  0.489319      0.006338 -0.05912

In [26]:
X_casas = base_casas.iloc[:,5:6].values
X_casas

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [27]:
y_casas = base_casas.iloc[:,2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [28]:
from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(X_casas, y_casas, test_size=0.3, random_state=0)

In [29]:
X_casas_treinamento.shape, y_casas_treinamento.shape

((15129, 1), (15129,))

In [30]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_casas_treinamento_poly = poly.fit_transform(X_casas_treinamento)
X_casas_teste_poly = poly.fit_transform(X_casas_teste)

In [31]:
X_casas_treinamento_poly.shape, X_casas_teste_poly.shape

((15129, 3), (6484, 3))

In [32]:
regressor_casas_poly = LinearRegression()
regressor_casas_poly.fit(X_casas_treinamento_poly, y_casas_treinamento)

LinearRegression()

In [33]:
regressor_casas_poly.score(X_casas_treinamento_poly, y_casas_treinamento)

0.5266754365257984

In [34]:
regressor_casas_poly.score(X_casas_teste_poly, y_casas_teste)

0.5440119730889537

In [35]:
previcoes =- regressor_casas_poly.predict(X_casas_teste_poly)
previcoes

array([ -375566.90351566, -1338412.22761335,  -377457.94420405, ...,
        -528825.73264338,  -385089.0236226 ,  -355207.10593201])

In [36]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [37]:
mean_absolute_error(y_casas_teste, previcoes)

1079468.6631097307

##Árvores de decisão

In [38]:
X_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [39]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [40]:
from sklearn.tree import DecisionTreeRegressor
regressor_arvore_saude = DecisionTreeRegressor()
regressor_arvore_saude.fit(X_plano_saude2, y_plano_saude2)


DecisionTreeRegressor()

In [41]:
previsoes = regressor_arvore_saude.predict(X_plano_saude2)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [42]:
regressor_arvore_saude.score(X_plano_saude2, y_plano_saude2)

1.0

In [43]:
grapth = px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
grapth.add_scatter(x=X_plano_saude2.ravel(), y=previsoes, name='Regressao')
grapth.show()

In [44]:
X_teste_arvore = np.arange(min(X_plano_saude2), max(X_plano_saude2), 0.1)
X_teste_arvore

<ipython-input-44-09c963292261>:1: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [45]:
X_teste_arvore.shape

(450,)

In [46]:
X_teste_arvore = X_teste_arvore.reshape(-1, 1)
X_teste_arvore.shape

(450, 1)

In [47]:
graph = px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
graph.add_scatter(x=X_teste_arvore.ravel(), y=regressor_arvore_saude.predict(X_teste_arvore), name='Regressao')
graph.show()

In [48]:
regressor_arvore_saude.predict([[40.6]])

array([1530.])

##Dataset home prices

In [49]:
X_casas_treinamento.shape

(15129, 1)

In [50]:
y_casas_treinamento

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [51]:
X_casas_teste.shape

(6484, 1)

In [52]:
regressor_arvore_casas = DecisionTreeRegressor()
regressor_arvore_casas.fit(X_casas_treinamento, y_casas_treinamento)

DecisionTreeRegressor()

In [53]:
regressor_arvore_casas.score(X_casas_treinamento, y_casas_treinamento)

0.6333418801272528

In [54]:
regressor_arvore_casas.score(X_casas_teste, y_casas_teste)

0.4938582480846785

In [55]:
previsoes = regressor_arvore_casas.predict(X_casas_teste)
previsoes

array([ 371652.48148148, 1119000.        ,  367642.        , ...,
        509418.78      ,  430163.03571429,  368505.30588235])

In [56]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [57]:
mean_absolute_error(y_casas_teste, previcoes)

1079468.6631097307

##Random forest

In [58]:
X_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [59]:
from sklearn.ensemble import RandomForestRegressor
regressor_random_forest_saude = RandomForestRegressor(n_estimators=10)
regressor_random_forest_saude.fit(X_plano_saude2, y_plano_saude2)

RandomForestRegressor(n_estimators=10)

In [60]:
regressor_random_forest_saude.score(X_plano_saude2,y_plano_saude2)

0.9912306629371821

In [61]:
X_teste_arvore

array([[18. ],
       [18.1],
       [18.2],
       [18.3],
       [18.4],
       [18.5],
       [18.6],
       [18.7],
       [18.8],
       [18.9],
       [19. ],
       [19.1],
       [19.2],
       [19.3],
       [19.4],
       [19.5],
       [19.6],
       [19.7],
       [19.8],
       [19.9],
       [20. ],
       [20.1],
       [20.2],
       [20.3],
       [20.4],
       [20.5],
       [20.6],
       [20.7],
       [20.8],
       [20.9],
       [21. ],
       [21.1],
       [21.2],
       [21.3],
       [21.4],
       [21.5],
       [21.6],
       [21.7],
       [21.8],
       [21.9],
       [22. ],
       [22.1],
       [22.2],
       [22.3],
       [22.4],
       [22.5],
       [22.6],
       [22.7],
       [22.8],
       [22.9],
       [23. ],
       [23.1],
       [23.2],
       [23.3],
       [23.4],
       [23.5],
       [23.6],
       [23.7],
       [23.8],
       [23.9],
       [24. ],
       [24.1],
       [24.2],
       [24.3],
       [24.4],
       [24.5],
       [24

In [62]:
grapth = px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
grapth.add_scatter(x=X_teste_arvore.ravel(), y=regressor_random_forest_saude.predict(X_teste_arvore), name='Regressao')
grapth.show()

In [63]:
regressor_random_forest_saude.predict([[40]])

array([1194.])

##Dataset house prices

In [64]:
X_casas_teste

array([[1430],
       [4670],
       [1440],
       ...,
       [2150],
       [1480],
       [1320]])

In [65]:
regressor_random_orest_casas = RandomForestRegressor(n_estimators=100)
regressor_random_orest_casas.fit(X_casas_treinamento, y_casas_treinamento)

RandomForestRegressor()

In [66]:
regressor_random_orest_casas.score(X_casas_treinamento, y_casas_treinamento)

0.6209012231733613

In [67]:
regressor_random_orest_casas.score(X_casas_teste, y_casas_teste)

0.5068726624164862

In [68]:
privisoes = regressor_random_orest_casas.predict(X_casas_teste)
privisoes

array([ 370656.62438854, 1169629.41666667,  367239.78239572, ...,
        505510.1660714 ,  432743.79687821,  369182.34075633])

In [69]:
mean_absolute_error(y_casas_teste, privisoes)

168797.87407860445

##SVM

###Dataset health plan

In [70]:
X_plano_saude2, y_plano_saude2

(array([[18],
        [23],
        [28],
        [33],
        [38],
        [43],
        [48],
        [53],
        [58],
        [63]]),
 array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
        10100]))

In [71]:
#Linear Kernel
from sklearn.svm import SVR
regressor_svr_saude = SVR(kernel='linear')
regressor_svr_saude.fit(X_plano_saude2, y_plano_saude2)

SVR(kernel='linear')

In [72]:
graph = px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
graph.add_scatter(x=X_plano_saude2.ravel(), y=regressor_svr_saude.predict(X_plano_saude2), name='Regressao')
graph.show()

In [73]:
#Polinomeal kernel
regressor_srv_poly = SVR(kernel='poly', degree=7)
regressor_srv_poly.fit(X_plano_saude2, y_plano_saude2)

SVR(degree=7, kernel='poly')

In [74]:
graph = px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
graph.add_scatter(x=X_plano_saude2.ravel(), y=regressor_srv_poly.predict(X_plano_saude2), name='Regressao')
graph.show()

In [75]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X_plano_saude2_scaled = scaler_x.fit_transform(X_plano_saude2)
scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1,1))


In [76]:
X_plano_saude2_scaled, y_plano_saude2_scaled

(array([[-1.5666989 ],
        [-1.21854359],
        [-0.87038828],
        [-0.52223297],
        [-0.17407766],
        [ 0.17407766],
        [ 0.52223297],
        [ 0.87038828],
        [ 1.21854359],
        [ 1.5666989 ]]),
 array([[-0.72401136],
        [-0.7065653 ],
        [-0.66818397],
        [-0.59839975],
        [-0.48674498],
        [-0.35415495],
        [-0.17620517],
        [ 0.18667281],
        [ 0.8914935 ],
        [ 2.63609918]]))

In [77]:
#Kernel rbf
regressor_svr_saude_rbf = SVR(kernel='rbf')
regressor_svr_saude_rbf.fit(X_plano_saude2_scaled, y_plano_saude2_scaled.ravel())

SVR()

In [78]:
graph = px.scatter(x=X_plano_saude2_scaled.ravel(), y=y_plano_saude2_scaled.ravel())
graph.add_scatter(x=X_plano_saude2_scaled.ravel(), y=regressor_svr_saude_rbf.predict(X_plano_saude2_scaled), name='Regressao')
graph.show()

In [79]:
novo = [[40]]

In [80]:
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [81]:
scaler_y.inverse_transform(regressor_svr_saude_rbf.predict(novo.reshape(-1, 1)).reshape(-1, 1)) # Reshape the output of the prediction to be a 2D array

array([[1333.85650748]])

##Dataset home

In [82]:
X_casas_treinamento.shape, y_casas_treinamento.shape

((15129, 1), (15129,))

In [83]:
y_casas_treinamento

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [84]:
X_casas_teste

array([[1430],
       [4670],
       [1440],
       ...,
       [2150],
       [1480],
       [1320]])

In [103]:
from sklearn.preprocessing import StandardScaler
scaler_x_casas = StandardScaler()
X_casas_treinamento_scaled = scaler_x_casas.fit_transform(X_casas_treinamento)
scaler_y_casas = StandardScaler()
y_casas_treinamento_scaled = scaler_y_casas.fit_transform(y_casas_treinamento.reshape(-1,1))

In [104]:
X_casas_treinamento_scaled, y_casas_treinamento_scaled

(array([[-0.74522967],
        [-0.68028398],
        [ 0.84593978],
        ...,
        [ 0.30472568],
        [ 0.31554996],
        [ 0.32637425]]),
 array([[-0.38454326],
        [-0.3024967 ],
        [ 0.49062008],
        ...,
        [-0.29976181],
        [-0.35445952],
        [ 0.43564888]]))

In [105]:
X_casas_teste_scaled = scaler_x_casas.transform(X_casas_teste)
y_casas_teste_scaled = scaler_y_casas.transform(y_casas_teste.reshape(-1,1))

In [106]:
X_casas_teste_scaled

array([[-0.70193254],
       [ 2.80513482],
       [-0.69110826],
       ...,
       [ 0.07741576],
       [-0.64781113],
       [-0.82099964]])

In [107]:
y_casas_treinamento_scaled

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [108]:
regressor_svr_casas = SVR(kernel='rbf')
regressor_svr_casas.fit(X_casas_treinamento_scaled, y_casas_treinamento_scaled.ravel())

SVR()

In [109]:
X_casas_teste_scaled.shape, y_casas_teste_scaled

((6484, 1),
 array([[-0.66623646],
        [ 2.83715179],
        [ 0.05878167],
        ...,
        [-0.43924097],
        [-0.74554814],
        [-0.91511104]]))

In [110]:
regressor_svr_casas.score(X_casas_treinamento_scaled, y_casas_treinamento_scaled)

0.5117557692887835

In [111]:
regressor_svr_casas.score(X_casas_teste_scaled, y_casas_teste_scaled)

0.48244979413787625

In [112]:
previsoes = regressor_svr_casas.predict(X_casas_teste_scaled)
previsoes

array([-0.46934709,  2.22606739, -0.46597917, ..., -0.16944439,
       -0.45270264, -0.50819424])

In [113]:
y_casas_teste_scaled

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [120]:
y_casas_teste_inverse = scaler_y_casas.inverse_transform(y_casas_teste_scaled)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes.reshape(-1,1))

In [121]:
y_casas_teste_inverse

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [122]:
previsoes_inverse

array([[ 368991.81492428],
       [1354559.41586376],
       [ 370223.28361423],
       ...,
       [ 478650.04631033],
       [ 375077.79513923],
       [ 354787.51197333]])

In [123]:
mean_absolute_error(y_casas_teste_inverse, previsoes_inverse)

163063.53601515805

##Artificial Neural Network

In [127]:
from sklearn.neural_network import MLPRegressor
regressor_rna_saude = MLPRegressor(max_iter=1000)
regressor_rna_saude.fit(X_plano_saude2_scaled, y_plano_saude2_scaled.ravel())

MLPRegressor(max_iter=1000)

In [128]:
regressor_rna_saude.score(X_plano_saude2_scaled, y_plano_saude2_scaled)

0.9589214695266826

In [130]:
grapth = px.scatter(x=X_plano_saude2_scaled.ravel(), y=y_plano_saude2_scaled.ravel())
grapth.add_scatter(x=X_plano_saude2_scaled.ravel(), y=regressor_rna_saude.predict(X_plano_saude2_scaled), name='Regressao')
grapth.show()

In [132]:
novo = [[40]]
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [136]:
scaler_y.inverse_transform(regressor_rna_saude.predict(scaler_x.transform(novo)).reshape(-1,1))

array([[-136.97657752]])

##House dataset

In [137]:
y_casas_treinamento_scaled

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [138]:
X_casas_teste_scaled.shape

(6484, 1)

In [139]:
(16+1)/2

8.5

In [140]:
regressor_rna_casas = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9,9))
regressor_rna_casas.fit(X_casas_treinamento_scaled, y_casas_treinamento_scaled.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [141]:
regressor_rna_casas.score(X_casas_treinamento_scaled, y_casas_treinamento_scaled)

0.5376264489889488

In [142]:
regressor_rna_casas.score(X_casas_teste_scaled, y_casas_teste_scaled)

0.5373996391022902

In [144]:
previsoes = regressor_rna_casas.predict(X_casas_teste_scaled)

In [146]:
y_casas_teste_inverse = scaler_y_casas.inverse_transform(y_casas_teste_scaled)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes.reshape(-1,1))

In [148]:
y_casas_teste_inverse

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [147]:
previsoes_inverse

array([[ 385064.9676897 ],
       [1497045.39478706],
       [ 386544.98153933],
       ...,
       [ 507585.80690477],
       [ 392465.03693788],
       [ 368784.8153437 ]])

In [149]:
mean_absolute_error(y_casas_teste_inverse, previsoes_inverse)

166134.7356395237