<a href="https://colab.research.google.com/github/pedro162/machine_learn/blob/main/machine_learn_outros_tipos_regressao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [18]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

In [19]:
from sklearn.linear_model import LinearRegression

In [56]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

#Regressão polinomial

##Base plano de saúde

In [20]:
base_plano_saude2 = pd.read_csv('/content/drive/MyDrive/Bases de dados/plano_saude2.csv')

In [21]:
base_plano_saude2

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [22]:
X_plano_saude2 = base_plano_saude2.iloc[:,0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:,1].values

In [23]:
X_plano_saude2, y_plano_saude2

(array([[18],
        [23],
        [28],
        [33],
        [38],
        [43],
        [48],
        [53],
        [58],
        [63]]),
 array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
        10100]))

In [24]:
from sklearn.preprocessing import PolynomialFeatures

In [25]:
poly = PolynomialFeatures(degree = 4)
X_plano_saude2_poly = poly.fit_transform(X_plano_saude2)


In [26]:
X_plano_saude2.shape, X_plano_saude2_poly.shape

((10, 1), (10, 5))

In [27]:
X_plano_saude2_poly

array([[1.0000000e+00, 1.8000000e+01, 3.2400000e+02, 5.8320000e+03,
        1.0497600e+05],
       [1.0000000e+00, 2.3000000e+01, 5.2900000e+02, 1.2167000e+04,
        2.7984100e+05],
       [1.0000000e+00, 2.8000000e+01, 7.8400000e+02, 2.1952000e+04,
        6.1465600e+05],
       [1.0000000e+00, 3.3000000e+01, 1.0890000e+03, 3.5937000e+04,
        1.1859210e+06],
       [1.0000000e+00, 3.8000000e+01, 1.4440000e+03, 5.4872000e+04,
        2.0851360e+06],
       [1.0000000e+00, 4.3000000e+01, 1.8490000e+03, 7.9507000e+04,
        3.4188010e+06],
       [1.0000000e+00, 4.8000000e+01, 2.3040000e+03, 1.1059200e+05,
        5.3084160e+06],
       [1.0000000e+00, 5.3000000e+01, 2.8090000e+03, 1.4887700e+05,
        7.8904810e+06],
       [1.0000000e+00, 5.8000000e+01, 3.3640000e+03, 1.9511200e+05,
        1.1316496e+07],
       [1.0000000e+00, 6.3000000e+01, 3.9690000e+03, 2.5004700e+05,
        1.5752961e+07]])

In [28]:
X_plano_saude2_poly[0]

array([1.00000e+00, 1.80000e+01, 3.24000e+02, 5.83200e+03, 1.04976e+05])

In [29]:
regressor_saude_polinomial = LinearRegression()
regressor_saude_polinomial.fit(X_plano_saude2_poly, y_plano_saude2)

LinearRegression()

In [30]:
regressor_saude_polinomial.intercept_

16561.97463791193

In [32]:
regressor_saude_polinomial.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [33]:
novo = [[40]]

In [34]:
novo = poly.transform(novo)

In [35]:
regressor_saude_polinomial.predict(novo)

array([1335.33958015])

In [36]:
previsoes = regressor_saude_polinomial.predict(X_plano_saude2_poly)
previsoes

array([ 549.65035464,  345.85081575,  616.53845992,  975.8391595 ,
       1249.06759853, 1472.7272727 , 1894.51048941, 2973.2983677 ,
       5379.16083828, 9993.35664357])

In [37]:
grafiaco = px.scatter(x=X_plano_saude2[:,0], y=y_plano_saude2)
grafiaco.add_scatter(x=X_plano_saude2[:,0], y=previsoes, name='Regressao')
grafiaco.show()

##Base preço das casas

In [39]:
base_casas = pd.read_csv("/content/drive/MyDrive/Bases de dados/house_prices.csv")
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [41]:
base_casas_clone = base_casas.apply(pd.to_numeric, errors='coerce')
base_casas_clone.corr()

id  date     price  bedrooms  bathrooms  sqft_living  \
id             1.000000   NaN -0.016762  0.001286   0.005160    -0.012258   
date                NaN   NaN       NaN       NaN        NaN          NaN   
price         -0.016762   NaN  1.000000  0.308350   0.525138     0.702035   
bedrooms       0.001286   NaN  0.308350  1.000000   0.515884     0.576671   
bathrooms      0.005160   NaN  0.525138  0.515884   1.000000     0.754665   
sqft_living   -0.012258   NaN  0.702035  0.576671   0.754665     1.000000   
sqft_lot      -0.132109   NaN  0.089661  0.031703   0.087740     0.172826   
floors         0.018525   NaN  0.256794  0.175429   0.500653     0.353949   
waterfront    -0.002721   NaN  0.266369 -0.006582   0.063744     0.103818   
view           0.011592   NaN  0.397293  0.079532   0.187737     0.284611   
condition     -0.023783   NaN  0.036362  0.028472  -0.124982    -0.058753   
grade          0.008130   NaN  0.667434  0.356967   0.664983     0.762704   
sqft_above    -0.010842   NaN  0.605567  0.477600   0.685342     0.876597   
sqft_basement -0.005151   NaN  0.323816  0.303093   0.283770     0.435043   
yr_built       0.021380   NaN  0.054012  0.154178   0.506019     0.318049   
yr_renovated  -0.016907   NaN  0.126434  0.018841   0.050739     0.055363   
zipcode       -0.008224   NaN -0.053203 -0.152668  -0.203866    -0.199430   
lat           -0.001891   NaN  0.307003 -0.008931   0.024573     0.052529   
long           0.020799   NaN  0.021626  0.129473   0.223042     0.240223   
sqft_living15 -0.002901   NaN  0.585379  0.391638   0.568634     0.756420   
sqft_lot15    -0.138798   NaN  0.082447  0.029244   0.087175     0.183286   

               sqft_lot    floors  waterfront      view  ...     grade  \
id            -0.132109  0.018525   -0.002721  0.011592  ...  0.008130   
date                NaN       NaN         NaN       NaN  ...       NaN   
price          0.089661  0.256794    0.266369  0.397293  ...  0.667434   
bedrooms       0.031703  0.175429   -0.006582  0.079532  ...  0.356967   
bathrooms      0.087740  0.500653    0.063744  0.187737  ...  0.664983   
sqft_living    0.172826  0.353949    0.103818  0.284611  ...  0.762704   
sqft_lot       1.000000 -0.005201    0.021604  0.074710  ...  0.113621   
floors        -0.005201  1.000000    0.023698  0.029444  ...  0.458183   
waterfront     0.021604  0.023698    1.000000  0.401857  ...  0.082775   
view           0.074710  0.029444    0.401857  1.000000  ...  0.251321   
condition     -0.008958 -0.263768    0.016653  0.045990  ... -0.144674   
grade          0.113621  0.458183    0.082775  0.251321  ...  1.000000   
sqft_above     0.183512  0.523885    0.072075  0.167649  ...  0.755923   
sqft_basement  0.015286 -0.245705    0.080588  0.276947  ...  0.168392   
yr_built       0.053080  0.489319   -0.026161 -0.053440  ...  0.446963   
yr_renovated   0.007644  0.006338    0.092885  0.103917  ...  0.014414   
zipcode       -0.129574 -0.059121    0.030285  0.084827  ... -0.184862   
lat           -0.085683  0.049614   -0.014274  0.006157  ...  0.114084   
long           0.229521  0.125419   -0.041910 -0.078400  ...  0.198372   
sqft_living15  0.144608  0.279885    0.086463  0.280439  ...  0.713202   
sqft_lot15     0.718557 -0.011269    0.030703  0.072575  ...  0.119248   

               sqft_above  sqft_basement  yr_built  yr_renovated   zipcode  \
id              -0.010842      -0.005151  0.021380     -0.016907 -0.008224   
date                  NaN            NaN       NaN           NaN       NaN   
price            0.605567       0.323816  0.054012      0.126434 -0.053203   
bedrooms         0.477600       0.303093  0.154178      0.018841 -0.152668   
bathrooms        0.685342       0.283770  0.506019      0.050739 -0.203866   
sqft_living      0.876597       0.435043  0.318049      0.055363 -0.199430   
sqft_lot         0.183512       0.015286  0.053080      0.007644 -0.129574   
floors           0.523885      -0.245705  0.489319      0.006338 -0.05912

In [42]:
X_casas = base_casas.iloc[:,5:6].values
X_casas

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [43]:
y_casas = base_casas.iloc[:,2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [44]:
from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(X_casas, y_casas, test_size=0.3, random_state=0)

In [45]:
X_casas_treinamento.shape, y_casas_treinamento.shape

((15129, 1), (15129,))

In [47]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_casas_treinamento_poly = poly.fit_transform(X_casas_treinamento)
X_casas_teste_poly = poly.fit_transform(X_casas_teste)

In [48]:
X_casas_treinamento_poly.shape, X_casas_teste_poly.shape

((15129, 3), (6484, 3))

In [49]:
regressor_casas_poly = LinearRegression()
regressor_casas_poly.fit(X_casas_treinamento_poly, y_casas_treinamento)

LinearRegression()

In [51]:
regressor_casas_poly.score(X_casas_treinamento_poly, y_casas_treinamento)

0.5266754365257984

In [52]:
regressor_casas_poly.score(X_casas_teste_poly, y_casas_teste)

0.5440119730889537

In [53]:
previcoes =- regressor_casas_poly.predict(X_casas_teste_poly)
previcoes

array([ -375566.90351566, -1338412.22761335,  -377457.94420405, ...,
        -528825.73264338,  -385089.0236226 ,  -355207.10593201])

In [54]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [57]:
mean_absolute_error(y_casas_teste, previcoes)

1079468.6631097307